import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
	currentLanguage: Language
	setLanguage: (lang: Language) => void
	t: (key: string) => string | string[]
}

const translations = {
	en: {
		// Free Plan
		'downgrade': 'Current Plan',
		'free_plan': 'Free Plan',
		'free': 'Free',
		'free_feature_1': 'Basic AI Chat',
		'free_feature_2': 'Limited API Access',
		'free_feature_3': 'Community Support',
		// Profile Page
		'phone_number': 'Phone Number',
		'enter_phone': 'Enter your phone number',
		'invalid_phone': 'Please enter a valid phone number',
		'invalid_email': 'Please enter a valid email address',
		'username_only_letters': 'Username can only contain letters',
		'username_min_length': 'Username must be at least 3 characters long',
		'profile_description': 'Manage your account settings and preferences',
		'profile_updated_successfully': 'Profile updated successfully',
		'member_since': 'Member since',
		'edit': 'Edit',
		'enter_username': 'Enter your username',
		'email': 'Email',
		'cancel': 'Cancel',
		'saving': 'Saving...',
		'save_changes': 'Save Changes',
		'security': 'Security',
		'last_changed': 'Last changed',
		'change_password': 'Change Password',
		'current_password': 'Current Password',
		'new_password': 'New Password',
		'confirm_password': 'Confirm Password',
		'updating': 'Updating...',
		'update_password': 'Update Password',
		'passwords_dont_match': 'Passwords do not match',
		'password_too_short': 'Password must be at least 8 characters',
		'error_changing_password': 'Error changing password',
		'connected_services': 'Connected Services',
		'no_connected_services': 'No services connected to your account',
		'api_calls_per_month': 'API calls per month',
		'model_access': 'Model access',

		// DeepSeek Model
		'deepseek_description': 'DeepSeek-R1-Distill-Qwen-32B, distilled from DeepSeek-R1, outperforms OpenAI-o1-mini.',
		// Auth Popup
		'login': 'Login',
		'register': 'Register',
		'login_subtitle': 'Welcome back! Please login to your account',
		'register_subtitle': 'Create your account to get started',
		'username': 'Username',
		'auth_email': 'Email',
		'password': 'Password',
		'username_placeholder': 'Enter your username',
		'auth_email_placeholder': 'Enter your email',
		'password_placeholder': 'Enter your password',
		'login_button': 'Login',
		'register_button': 'Create Account',
		'need_account': 'Need an account? Register',
		'have_account': 'Already have an account? Login',
		'auth_required_to_use_ai': 'Please login or register to use our AI features',
		'login_error': 'Invalid email or password',
		'registration_error': 'Error creating account. Please try again',
		'username_required': 'Username is required',
		'username_taken': 'Username is already taken',
		'auth_error': 'Authentication error. Please try again',

		// Navigation
		'dashboard': 'Dashboard',
		'profile': 'Profile',
		'subscription': 'Subscription',
		'subscription_management': 'Subscription Management',
		'subscription_management_description': 'Manage your subscription plan and billing details',
		'current_subscription': 'Current Subscription',
		'started_on': 'Started on',
		'next_billing_date': 'Next billing date',
		'cancel_subscription': 'Cancel Subscription',
		'confirm_cancel': 'Confirm Cancel',
		'keep_subscription': 'Keep Subscription',
		'subscription_auto_renew_notice': 'Your subscription will automatically renew at the end of the billing period',
		'subscription_cancelled': 'Subscription cancelled successfully',
		'subscription_updated': 'Subscription updated successfully',
		'change_plan': 'Change Plan',
		'current_plan': 'Current Plan',
		'need_enterprise_features': 'Need Enterprise Features?',
		'enterprise_custom_description': 'Get a custom plan tailored to your organization\'s needs',
		'contact_our_sales_team': 'Contact Our Sales Team',
		'explore_models': 'Explore Models',
		'try_demo': 'Try Demo',
		'docs': 'Docs',
		'pricing': 'Pricing',
		'contact': 'Contact',
		'about': 'About',
		'privacy': 'Privacy',
		'terms': 'Terms',

		// Settings
		'language': 'Language',
		'english': 'English',
		'spanish': 'Spanish',
		'french': 'French',
		'german': 'German',
		'chinese': 'Chinese',
		'japanese': 'Japanese',
		'coming_soon': 'Coming Soon',
		'theme': 'Theme',
		'graph_animation': 'Graph Animation',
		'snow_effect': 'Snow Effect',
		'settings': 'Settings',
		'settings_description': 'Manage your account settings and preferences',
		'settings_saved_successfully': 'Settings saved successfully',
		'dark_mode': 'Dark Mode',
		'dark_mode_description': 'Enable or disable dark mode',
		'neural_network_background': 'Neural Network Background',
		'neural_network_description': 'Enable or disable the neural network background animation',
		'email_notifications': 'Email Notifications',
		'email_notifications_description': 'Receive updates and notifications via email',
		'manage': 'Manage',
		'usage_metrics': 'Usage Metrics',
		'ai_tools_hub': 'AI Tools Hub',
		'explore_available_tools': 'Explore available AI tools',
		'explore_tools': 'Explore Tools',
		'billing_management': 'Billing Management',
		'view_billing_history': 'View Billing History',
		'manage_payment_methods': 'Manage Payment Methods',
		'api_keys_description': 'Manage your API keys for accessing AI services',
		'save_settings': 'Save Settings',

		// Home Page
		'hero_subtitle': 'Access state-of-the-art AI models through a single, unified platform. Build smarter applications with our comprehensive suite of AI services.',
		'get_started_button': 'Get Started',
		'api_keys': 'API Keys',
		'appearance': 'Appearance',
		'notifications': 'Notifications',
		'learn_more': 'Learn More',

		// Dashboard Section
		'dashboard_title': 'Powerful Analytics Dashboard',
		'dashboard_subtitle': 'Monitor your AI models\' performance, usage, and metrics in real-time with our intuitive dashboard.',

		// Features Section
		'language_models_title': 'Language Models',
		'language_models_desc': 'Access powerful language models for natural conversations, content generation, and more.',
		'image_generation_title': 'Image Generation',
		'image_generation_desc': 'Create stunning visuals from text descriptions with state-of-the-art image generation models.',
		'speech_recognition_title': 'Speech Recognition',
		'speech_recognition_desc': 'Convert speech to text with high accuracy across multiple languages and accents.',
		'try_it_now': 'Try it now',

		// Pricing Page
		'pricing_title': 'Simple, Transparent Pricing',
		'pricing_subtitle': 'Choose the plan that best fits your needs',
		'starter_plan': 'Starter',
		'starter_feature_1': 'Access to basic models',
		'starter_feature_2': '5,000 API calls per month',
		'starter_feature_3': 'Standard support',
		'pro_plan': 'Professional',
		'pro_feature_1': 'Access to all models',
		'pro_feature_2': '50,000 API calls per month',
		'pro_feature_3': 'Priority support',
		'pro_feature_4': 'Advanced analytics',
		'enterprise_plan': 'Enterprise',
		'enterprise_feature_1': 'Unlimited API calls',
		'enterprise_feature_2': '24/7 dedicated support',
		'enterprise_feature_3': 'Custom model development',
		'enterprise_feature_4': 'SLA guarantees',
		'enterprise_feature_5': 'On-premise deployment',
		'monthly': 'monthly',
		'yearly': 'yearly',
		'monthly_billing': 'Monthly Billing',
		'yearly_billing': 'Yearly Billing',
		'save': 'Save',
		'current_plan_en': 'Current Plan',
		'upgrade': 'Get Started',
		'pricing_subscribe': 'Subscribe',
		'get_started_now': 'Get Started Now',
		'contact_sales': 'Contact Sales',
		'plan_free_description': 'Basic features for personal use',
		'plan_starter_description': 'Enhanced features for small teams',
		'plan_pro_description': 'Advanced features for businesses',
		'plan_enterprise_description': 'Full access for large organizations',
		'features_included': 'Features included',
		'api_calls_per_day': 'API calls per day',
		'support_level': 'Support level',
		'response_time': 'Response time',
		'basic_ai_chat': 'Basic AI Chat',
		'community_support': 'Community support',
		'standard_response_time': 'Standard response time',
		'pricing_starter_features': [
			'Access to basic models',
			'5,000 API calls per month',
			'Standard support',
			'Basic analytics'
		],
		'pricing_pro_features': [
			'Access to all models',
			'50,000 API calls per month',
			'Priority support',
			'Advanced analytics',
			'Custom model fine-tuning'
		],
		'pricing_enterprise_features': [
			'Unlimited API calls',
			'24/7 dedicated support',
			'Custom model development',
			'SLA guarantees',
			'On-premise deployment'
		],
		'faq_title': 'Frequently Asked Questions',
		'faq_q1': 'What payment methods do you accept?',
		'faq_a1': 'We accept all major credit cards, PayPal, and wire transfers for enterprise customers.',
		'faq_q2': 'Can I change my plan later?',
		'faq_a2': 'Yes, you can upgrade or downgrade your plan at any time. Changes will be reflected in your next billing cycle.',
		'faq_q3': 'Do you offer refunds?',
		'faq_a3': 'Yes, we offer a 30-day money-back guarantee for all our plans.',
		'faq_q4': 'What happens if I exceed my API limit?',
		'faq_a4': 'You will be notified when you reach 80% of your limit. Additional calls will be charged at our standard overage rates.',

		// Contact Page
		'contact_title': 'Get in Touch',
		'contact_subtitle': 'We\'d love to hear from you',
		'contact_page_name': 'Name',
		'contact_page_email': 'Email',
		'contact_page_message': 'Message',
		'send_message': 'Send Message',
		'contact_send_message': 'Send Message',

		// Footer
		'footer_description': 'Building the future of AI integration',
		'footer_resources': 'Resources',
		'footer_company': 'Company',
		'footer_legal': 'Legal',
		'footer_subscribe': 'Subscribe to our newsletter',
		'subscribe_desc': 'Get the latest updates and news directly in your inbox.',
		'enter_email': 'Enter your email',
		'subscribe_button': 'Subscribe',
		'all_rights_reserved': 'All rights reserved.',
		'social_media': 'Follow us',
		'twitter': 'Twitter',
		'github': 'GitHub',
		'linkedin': 'LinkedIn',

		// Suscripción y Uso
		"included_features": "Included Features",
		"100_api_calls_per_month": "100 API calls per month",
		"100_mb_storage": "100.00 MB of storage",
		"5_model_access": "Access to 5 models",
		"current_usage": "Current Usage",
		"api_calls": "API Calls",
		"storage": "Storage",
		"upgrade_plan": "Upgrade Plan",

		// Interactive Demo
		'demo_title': 'Interactive Demo',
		'demo_subtitle': 'Experience our AI models in action',
		'try_models': 'Try Our Models',
		'view_examples': 'View Examples',
		'generating': 'Generating...',

		// Models Page
		'models_title': 'AI Models Hub',
		'models_subtitle': 'Explore our collection of state-of-the-art AI models',
		'filter_models': 'Filter Models',
		'search_models': 'Search Models',
		'sort_by': 'Sort by',
		'category': 'Category',
		'all_categories': 'All Categories',
		'newest': 'Newest',
		'model_name': 'Name',
		'no_models_found': 'No models found in this category. Try selecting a different category.',
		'version': 'Version',
		'try_model': 'Try Model',

		// Model Categories
		'language_models': 'Language Models',
		'image_generation': 'Image Generation',
		'speech_recognition': 'Speech Recognition',
		'computer_vision': 'Computer Vision',
		'audio_processing': 'Audio Processing',

		// Model Details
		'model_description': 'Model Description',
		'features': 'Features',
		'specifications': 'Specifications',
		'requirements': 'Requirements',
		'documentation': 'Documentation',
		'api_endpoints': 'API Endpoints',
		'pricing_info': 'Pricing Information',
		'model_version': 'Model Version',
		'last_updated': 'Last Updated',
		'status': 'Status',
		'active': 'Active',
		'deprecated': 'Deprecated',
		'beta': 'Beta',

		// Sort Options
		'sort_popular': 'Most Popular',
		'sort_newest': 'Newest First',
		'sort_name': 'Name (A-Z)',
		'sort_rating': 'Highest Rated',

		// Status Messages
		'loading': 'Loading...',
		'error_loading': 'Error loading models',
		'try_again': 'Try Again',
		'no_results': 'No results found',
		'no_results_try_again': 'No results found. Try different search terms.',

		// Actions
		'view_details': 'View Details',
		'view_docs': 'View Documentation',

		// Authentication
		'sign_in': 'Sign In',
		'sign_up': 'Sign Up',
		'sign_out': 'Sign Out',
		'forgot_password': 'Forgot Password?',
		'reset_password': 'Reset Password',
		'reset_password_subtitle': 'Enter your email address to reset your password',
		'remember_me': 'Remember Me',
		'logout': 'Logout',

		// Form Labels
		'form_email': 'Email Address',
		'form_password': 'Password',
		'form_confirm_password': 'Confirm Password',
		'form_full_name': 'Full Name',
		'form_company': 'Company',
		'form_message': 'Message',
		'form_name': 'Name',

		// Documentation
		'docs_title': 'Documentation',
		'docs_subtitle': 'Learn how to integrate and use our AI models',
		'quick_start': 'Quick Start',
		'api_reference': 'API Reference',
		'examples': 'Examples',
		'guides': 'Guides',
		'install_ailive_sdk': 'Install the AILive SDK',
		'configure_api_key': 'Configure your API key',
		'make_first_api_call': 'Make your first API call',
		'authentication': 'Authentication',
		'endpoints': 'Endpoints',
		'response_formats': 'Response formats',
		'text_generation': 'Text generation',
		'image_processing': 'Image processing',
		'best_practices': 'Best practices',
		'error_handling': 'Error handling',
		'rate_limiting': 'Rate limiting',

		// Testimonials Section
		'testimonials_title': 'What Our Users Say',
		'testimonials_subtitle': 'Discover how AILive is transforming businesses worldwide',
		'testimonial_1_name': 'Sarah Johnson',
		'testimonial_1_role': 'CTO at TechCorp',
		'testimonial_1_text': 'The platform has streamlined our AI integration process and significantly reduced our time to market.',
		'testimonial_2_name': 'Michael Chen',
		'testimonial_2_role': 'Lead Developer at InnovateLabs',
		'testimonial_2_text': 'AILive has transformed our development workflow. The models are incredibly accurate and the API is a breeze to work with.',
		'testimonial_3_name': 'Emma Rodriguez',
		'testimonial_3_role': 'AI Research Director',
		'testimonial_3_text': 'The fine-tuning capabilities and model performance monitoring have exceeded our expectations. Highly recommended!',
		'testimonial_4_name': 'David Wilson',
		'testimonial_4_role': 'Director of Innovation',
		'testimonial_4_text': 'The model performance insights and optimization suggestions have helped us achieve remarkable improvements.',
		'testimonial_5_name': 'Laura Garcia',
		'testimonial_5_role': 'VP of Technology',
		'testimonial_5_text': 'Exceptional support team and comprehensive documentation. They\'ve made our AI journey smooth and successful.',
		'testimonial_6_name': 'Robert Martinez',
		'testimonial_6_role': 'CTO at TechCorp',
		'testimonial_6_text': 'The reliability and scalability of the platform have been crucial for our enterprise deployment.',

		// Interactive Demo Sections
		'demo_tabs_title': 'Try Our Models',
		'tab_text_generation': 'Text Generation',
		'tab_image_generation': 'Image Generation',
		'tab_speech_recognition': 'Speech Recognition',
		'tab_code_generation': 'Code Generation',
		'input_placeholder': 'Enter your prompt here...',
		'generate_button': 'Generate',
		'processing': 'Processing...',
		'sample_prompts': 'Sample Prompts',
		'clear_input': 'Clear',
		'copy_result': 'Copy',
		'download_result': 'Download',
		'share_result': 'Share',
		'model_settings': 'Model Settings',
		'temperature': 'Temperature',
		'max_length': 'Max Length',
		'frequency_penalty': 'Frequency Penalty',
		'presence_penalty': 'Presence Penalty',

		// Model Card Details
		'model_card_metrics': 'Model Performance Metrics',
		'model_card_latency': 'Latency',
		'model_card_availability': 'Availability',
		'model_card_accuracy_metric': 'Accuracy',
		'model_card_pricing': 'Pricing Plans',
		'model_card_starter': 'Starter',
		'model_card_pro': 'Professional',
		'model_card_enterprise': 'Enterprise',
		'model_card_features': 'Key Features',
		'model_card_try': 'Try Model',
		'model_card_learn_more': 'Learn More',
		'model_card_version_info': 'Version Information',
		'model_card_last_updated': 'Last Updated',
		'model_card_changelog': 'Changelog',
		'model_card_documentation': 'Documentation',
		'model_card_examples': 'Examples',
		'model_card_limitations': 'Limitations',
		'model_card_use_cases': 'Use Cases',
		'model_card_ready_to_start': 'Ready to Get Started?',
		'model_card_start_building': 'Start Building',
		'model_card_performance': 'Performance',
		'model_card_context_length': 'Context Length',
		'model_card_resolution': 'Resolution',
		'model_card_token_length': 'Token Length',
		'model_card_languages': 'Supported Languages',
		'model_card_starter_desc': 'Basic access with standard features',
		'model_card_pro_desc': 'Advanced features with priority support',
		'model_card_enterprise_desc': 'Custom solutions with dedicated support',
		'gpt4_desc': 'Latest GPT-4 model with enhanced capabilities',
		'llama2_desc': 'Open source LLM with competitive performance',
		'stable_diffusion_xl_desc': 'Advanced image generation with SDXL',
		'whisper_desc': 'Accurate speech recognition across languages',
		'dalle3_desc': 'State-of-the-art image generation with DALL·E 3',
		'llama_desc': 'High-performance open source language model',

		// Interactive Demo Page
		'demo_text_generation_desc': 'Experience the power of our most advanced language model.',
		'demo_image_generation_desc': 'Generate stunning images from text descriptions.',
		'demo_speech_recognition_desc': 'Convert speech to text with exceptional accuracy.',
		'demo_code_generation_desc': 'Generate code with our efficient and powerful model.',
		'demo_input_placeholder': 'Enter your prompt here...',
		'demo_send_message': 'Send Message',
		'generated_image': 'Generated image',
		'start_recording': 'Start Recording',
		'stop_recording': 'Stop Recording',

		// Model Features
		'feature_natural_language': 'Natural Language Processing',
		'feature_content_generation': 'Content Generation',
		'feature_code_assistance': 'Code Assistance',
		'feature_text_to_image': 'Text to Image Generation',
		'feature_image_editing': 'Image Editing',
		'feature_style_transfer': 'Style Transfer',
		'feature_speech_to_text': 'Speech to Text',
		'feature_language_detection': 'Language Detection',
		'feature_accent_handling': 'Accent Handling',
		'feature_image_generation': 'Image Generation',
		'feature_inpainting': 'Image Inpainting',
		'feature_outpainting': 'Image Outpainting',
		'feature_task_assistance': 'Task Assistance',
		'feature_research': 'Research',
		'feature_analysis': 'Analysis',
		'feature_text_generation': 'Text Generation',
		'feature_translation': 'Translation',
		'feature_classification': 'Classification',

		// Technical Specifications Translations
		// Architecture
		'gpt4_architecture_1': 'Transformer-based architecture with 1.76T parameters',
		'gpt4_architecture_2': 'Multi-modal capabilities with text and image understanding',
		'dalle3_architecture_1': 'Diffusion-based image generation with advanced CLIP guidance',
		'dalle3_architecture_2': 'Advanced image composition and style preservation',
		'whisper_architecture_1': 'Encoder-decoder architecture with multilingual support',
		'whisper_architecture_2': 'Robust noise resistance and accent adaptation',
		'stable_diffusion_architecture_1': 'Latent diffusion model with UNet backbone',
		'stable_diffusion_architecture_2': 'Memory-efficient training and inference',
		'claude_architecture_1': 'Constitutional AI with advanced reasoning capabilities',
		'claude_architecture_2': 'Advanced context understanding and task adaptation',
		'llama_architecture_1': 'Open-source transformer with efficient scaling',
		'llama_architecture_2': 'Efficient parameter scaling and fine-tuning capabilities',

		// Capabilities
		'gpt4_capability_1': 'Advanced reasoning and problem-solving abilities',
		'gpt4_capability_2': 'Context-aware responses with high accuracy',
		'dalle3_capability_1': 'Photorealistic image generation with precise details',
		'dalle3_capability_2': 'Advanced composition and artistic style control',
		'whisper_capability_1': 'Accurate transcription in 100+ languages',
		'whisper_capability_2': 'Real-time transcription and translation',
		'stable_diffusion_capability_1': 'High-quality image generation and editing',
		'stable_diffusion_capability_2': 'Fast inference with quality results',
		'claude_capability_1': 'Complex task completion and analysis',
		'claude_capability_2': 'Detailed explanations and reasoning',
		'llama_capability_1': 'Efficient language understanding and generation',
		'llama_capability_2': 'Customizable for specific use cases',

		// Model-Specific Translations
		'tab_claude': 'Claude Assistant',
		'claude_desc': 'Anthropic\'s advanced AI assistant focused on helpful, honest, and safe interactions',
		'claude_input_placeholder': 'Ask Claude anything...',
		'claude_demo_response': 'I aim to be helpful while being direct and honest. I\'ll assist you with analysis, writing, and various tasks while maintaining high ethical standards.',
		'tab_stable_diffusion': 'Stable Diffusion',
		"stable_diffusion_desc": "Advanced image generation with precise control and high-quality outputs.",
		"stable_diffusion_prompt_placeholder": "Describe the image you want to generate in detail...",
		'deepseek_input_placeholder': 'Enter your prompt for DeepSeek...',
		'top_p': 'Top P',
		'max_tokens': 'Max Tokens',
		'top_k': 'Top K',
		"deepseek_model_description": "DeepSeek-R1-Distill-Qwen-32B is a distilled model of DeepSeek-R1 based on Qwen2.5. It outperforms OpenAI-o1-mini on several benchmarks.",
		"stable_diffusion_negative_placeholder": "Describe what you don't want to see in the image...",
		"positive_prompt": "Positive Prompt",
		"negative_prompt": "Negative Prompt",
		"steps": "Generation Steps",
		"guidance_scale": "Guidance Scale",
		"gpt_demo_response": "This is a simulated response from GPT-4. In a real implementation, this would be connected to the actual API.",
		"llama_demo_response": "This is a simulated response from LLaMA using temperature {temp} and maximum tokens {tokens}.",
		"speech_demo_transcript": "This is a simulated transcript. In a real implementation, this would use the Web Speech API or similar.",
		"llama_input_placeholder": "Enter your prompt for LLaMA...",
		"image_input_placeholder": "Describe the image you want to generate...",

		// Trusted Section
		'trusted_title': 'Trusted by Industry Leaders',
		'trusted_description': 'Join thousands of companies worldwide who trust our AI solutions',
		'trusted_card_1_title': 'Enterprise Solutions',
		'trusted_card_1_desc': 'Customized AI integration for large-scale operations',
		'trusted_card_2_title': 'Developer Tools',
		'trusted_card_2_desc': 'Powerful APIs and SDKs for seamless implementation',
		'trusted_card_3_title': 'Support & Training',
		'trusted_card_3_desc': 'Comprehensive resources and expert assistance',

		// Carousel
		'carousel_explore': 'Explore AI Models',
		'carousel_why_choose': 'Why Choose AILive?',
		'carousel_close': 'Close',
		'carousel_prev': 'Previous',
		'carousel_next': 'Next',

		// About Page
		'about_title': 'About AILive',
		'about_subtitle': 'Empowering Innovation Through AI',
		'about_description': 'AILive is a leading platform providing state-of-the-art AI models and solutions. Our mission is to make advanced AI technology accessible and practical for businesses of all sizes.',
		'about_vision': 'Our Vision',
		'about_vision_text': 'To democratize AI technology and drive innovation across industries.',
		'about_mission': 'Our Mission',
		'about_mission_text': 'Providing cutting-edge AI solutions that are accessible, reliable, and ethical.',
		'about_values': 'Our Values',
		'about_values_1': 'Innovation',
		'about_values_1_text': 'Constantly pushing the boundaries of AI technology',
		'about_values_2': 'Reliability',
		'about_values_2_text': 'Delivering consistent and dependable solutions',
		'about_values_3': 'Ethics',
		'about_values_3_text': 'Maintaining high standards of AI ethics and responsibility',

		// Terms Page
		'terms_title': 'Terms of Service',
		'terms_last_updated': 'Last Updated',
		'terms_table_of_contents': 'Table of Contents',
		'terms_intro': 'Please read these terms of service carefully before using our platform.',
		'terms_acceptance': 'By accessing or using our service, you agree to be bound by these terms.',
		'terms_section_1': 'Usage Terms',
		'terms_section_2': 'User Responsibilities',
		'terms_section_3': 'Service Limitations',
		'terms_section_4': 'Intellectual Property',
		'terms_section_5': 'Privacy & Data',
		'terms_usage_1': 'Access and use of our AI models is subject to these terms',
		'terms_usage_2': 'You must maintain valid authentication credentials',
		'terms_usage_3': 'Usage is limited to your approved quota and rate limits',
		'terms_usage_4': 'You may not reverse engineer or decompile our services',
		'terms_responsibility_1': 'You are responsible for all activity under your account',
		'terms_responsibility_2': 'You must not use our services for illegal purposes',
		'terms_responsibility_3': 'You must protect your API keys and credentials',
		'terms_responsibility_4': 'You must comply with all applicable laws and regulations',
		'terms_limitation_1': 'Services are provided "as is" without warranty',
		'terms_limitation_2': 'We may modify or discontinue services at any time',
		'terms_limitation_3': 'We may impose usage limits or restrictions',
		'terms_limitation_4': 'Service availability and performance may vary',
		'terms_intellectual_1': 'We retain all rights to our services and technology',
		'terms_intellectual_2': 'You retain rights to your input data',
		'terms_intellectual_3': 'Generated content licensing terms apply',
		'terms_intellectual_4': 'You may not use our trademarks without permission',
		'terms_privacy_1': 'We process data as described in our Privacy Policy',
		'terms_privacy_2': 'You must have rights to data you submit',
		'terms_privacy_3': 'We may collect usage data and analytics',
		'terms_privacy_4': 'Data retention policies apply',

		// Privacy Page
		'privacy_title': 'Privacy Policy',
		'privacy_last_updated': 'Last Updated',
		'privacy_intro': 'We take your privacy seriously. This policy explains how we collect, use, and protect your personal information.',
		'privacy_section_1': 'Data Collection',
		'privacy_section_2': 'Data Usage',
		'privacy_section_3': 'Data Protection',
		'privacy_section_4': 'User Rights',
		'privacy_section_5': 'Contact Information',
		'privacy_collection_1': 'We collect information you provide directly to us when using our services.',
		'privacy_collection_2': 'We automatically collect certain information about your device and usage of our services.',
		'privacy_collection_3': 'We use cookies and similar tracking technologies to enhance your experience.',
		'privacy_collection_4': 'We may collect information from third-party services with your consent.',
		'privacy_usage_1': 'We use your information to provide and improve our services.',
		'privacy_usage_2': 'Your data helps us personalize and optimize your experience.',
		'privacy_usage_3': 'We analyze usage patterns to enhance our platform\'s functionality.',
		'privacy_usage_4': 'We may use your information for marketing purposes with your consent.',
		'privacy_protection_1': 'We implement industry-standard security measures to protect your data.',
		'privacy_protection_2': 'Your information is encrypted during transmission and storage.',
		'privacy_protection_3': 'We regularly review and update our security practices.',
		'privacy_protection_4': 'Access to your data is strictly controlled and monitored.',
		'privacy_rights_1': 'You have the right to access your personal information.',
		'privacy_rights_2': 'You can request corrections to your data.',
		'privacy_rights_3': 'You may request deletion of your information.',
		'privacy_rights_4': 'You can opt-out of certain data processing activities.',
		'privacy_contact_1': 'For privacy-related inquiries, contact our Data Protection Officer.',
		'privacy_contact_2': 'Email us at privacy@ailive.com',
		'privacy_contact_3': 'Response time: Within 48 hours',
		'privacy_contact_4': 'We are committed to addressing your privacy concerns promptly.',

		// Testimonials Popup
		'testimonial_metrics': 'Performance Metrics',
		'testimonial_close': 'Close Details',
		'testimonial_rating': 'Rating',
		'testimonial_company': 'Company',
		'testimonial_role': 'Role',

		// Metrics Translations
		'metric_accuracy': 'Accuracy',
		'metric_responsetime': 'Response Time',
		'metric_uptime': 'Uptime',
		'metric_modelsdeployed': 'Models Deployed',
		'metric_averagelatency': 'Average Latency',
		'metric_successrate': 'Success Rate',
		'metric_throughput': 'Throughput',
		'metric_errorrate': 'Error Rate',
		'metric_costsavings': 'Cost Savings',
		'metric_timetomarket': 'Time to Market',
		'metric_usersatisfaction': 'User Satisfaction',
		'metric_roi': 'ROI',
		'metric_modelaccuracy': 'Model Accuracy',
		'metric_inferencespeed': 'Inference Speed',
		'metric_costreduction': 'Cost Reduction',
		'metric_apiuptime': 'API Uptime',
		'metric_integrationtime': 'Integration Time',
		'metric_supportresponse': 'Support Response',

		// Carousel Cards
		'carousel_card_1_title': 'Advanced AI Models',
		'carousel_card_1_desc': 'Access cutting-edge AI models through our unified platform',
		'carousel_card_2_title': 'Easy Integration',
		'carousel_card_2_desc': 'Simple API integration with comprehensive documentation',
		'carousel_card_3_title': 'Scalable Solutions',
		'carousel_card_3_desc': 'Enterprise-ready infrastructure that grows with you',

		// Carousel Popups
		'explore_models_title': 'Explore AI Models',
		'explore_models_desc': 'Discover our comprehensive suite of state-of-the-art AI models ready for integration',
		'why_choose_title': 'Why Choose AILive?',
		'why_choose_desc': 'Leading platform for AI integration with enterprise-grade reliability and support',

		// Card Descriptions in Popups
		'card_performance_title': 'High Performance',
		'card_performance_desc': 'Industry-leading accuracy and response times',
		'card_security_title': 'Enterprise Security',
		'card_security_desc': 'Advanced security features and compliance standards',
		'card_support_title': '24/7 Support',
		'card_support_desc': 'Dedicated technical support and documentation',

		'models_available': 'Models Available',
		'api_requests_daily': 'API Requests Daily',
		'enterprise_clients': 'Enterprise Clients',
		'uptime_sla': 'Uptime SLA',
		'stats_title': 'AILive by the Numbers',
		'ready_to_transform': 'Ready to transform your AI development workflow?',

		// Dashboard Metrics
		'dashboard_model_performance': 'AI Model Performance',
		'dashboard_accuracy': 'Accuracy',
		'dashboard_latency': 'Latency',
		'dashboard_uptime': 'Uptime',
		'dashboard_api_usage': 'API Usage',
		'dashboard_model_training': 'Model Training',

		// Contact Form Fields
		'contact_form_name': 'Name',
		'contact_form_email': 'Email',
		'contact_company_name': 'Company Name',
		'contact_phone': 'Phone Number',
		'contact_model': 'AI Model of Interest',
		'contact_message': 'Message',
		'contact_submit': 'Send Message',
		'contact_placeholder_name': 'Enter your name',
		'contact_placeholder_email': 'Enter your email',
		'contact_placeholder_company': 'Enter your company name',
		'contact_placeholder_phone': '+1 (555) 000-0000',
		'contact_placeholder_message': 'Enter your message',
		'contact_select_model': 'Select a model',

		// Contact Additional Info
		'contact_email_label': 'Email',
		'contact_phone_label': 'Phone',
		'contact_hours_label': 'Office Hours',
		'contact_hours_value': 'Mon-Fri, 9am-6pm EST',
		'multiple_models': 'Multiple Models',

		// Model Specifications
		'context_length': 'Context Length',
		'up_to': 'Up to',
		'tokens': 'tokens',
		'code_generation_desc': 'Generate efficient and maintainable code with our advanced models.',
		'model_context': 'Context',
		'supported': 'supported',
		'stable_diffusion': 'Stable Diffusion',
		'month_abbr': 'mo',

		// Language Settings
		'language_settings': 'Language Settings',
		'language_settings_description': 'Choose your preferred language',
		'language_english': 'English',
		'language_spanish': 'Spanish',
		'language_french': 'French',
		'language_german': 'German',
		'language_chinese': 'Chinese',
		'language_japanese': 'Japanese',
		'language_coming_soon': 'Coming Soon',
		'speech': 'Speech',
		'image': 'Image',
		'custom': 'Custom',

		// Subscription Features
		'browser_agent_description': 'AI-powered browser automation for seamless web interactions and data collection',
		'deep_research_description': 'Advanced AI research capabilities for comprehensive analysis and insights',
		'scraping_agent_description': 'Intelligent data extraction and form automation using advanced AI algorithms',
		'ai_assistant_description': 'Enhanced AI assistant with advanced capabilities and contextual understanding',
		'custom_models_description': 'Create and fine-tune custom AI models tailored to your specific needs',
		'subscription_type': 'Subscription Type',
		'subscriptions': 'Subscriptions',
		'enterprise_support_message': 'Get priority access to our dedicated support team 24/7',
		'huggingface_api_description': 'Access state-of-the-art AI models from Hugging Face for text generation, image processing, and more',
		'advanced_chat_description': 'Enhanced chat capabilities with context memory and 25 daily API calls for better conversations',
		'pro_chat_description': 'Professional chat system with advanced features, context understanding, and 100 daily API calls',
		'model_fine_tuning_description': 'Customize and optimize AI models with your own data for industry-specific solutions',
		'enterprise_chat_description': 'Enterprise-grade chat system with unlimited API calls, custom integrations, and dedicated support',

		// Dashboard
		'starter_dashboard_welcome': 'Welcome to Your Starter Dashboard',
		'pro_dashboard_welcome': 'Welcome to Your Pro Dashboard',
		'enterprise_dashboard_welcome': 'Welcome to Your Enterprise Dashboard',
		'enterprise_dashboard_subtitle': 'Access all premium features and custom solutions',
		'api_calls_remaining': 'API Calls Remaining',
		'unlimited': 'Unlimited',
		'customize_models': 'Customize Models',
		'launch_tool': 'Launch Tool',
		'enterprise_support': '24/7 Enterprise Support',
		'enterprise_support_description': 'Get priority support from our dedicated team of AI experts',
		'contact_support': 'Contact Support',
		'schedule_call': 'Schedule Call',

		// Subscription
		'subscription_plans': 'Choose Your AI Plan',
		'choose_plan_description': 'Select the plan that best fits your AI development needs',
		'subscription_monthly_billing': 'Monthly',
		'subscription_yearly_billing': 'Yearly',
		'subscription_save': 'Save',
		'subscription_with_yearly_billing': 'with yearly billing',
		'subscription_most_popular': 'Most Popular',
		'subscription_current_plan_en': 'Current Plan',
		'subscription_get_started': 'Get Started',
		'subscription_month': 'mo',
		'subscription_year': 'yr',
		'popular': 'Popular',
		'redirecting': 'Redirecting...',
		// Stable Diffusion
		"stable_diffusion_negative_prompt_placeholder": "Enter the elements you do NOT want to see in the image (optional).",
		"generate_image": "Generate Image",

		'enter_api_key': 'Enter API Key',
		'save_api_key': 'Save API Key',
		'custom_api_key': 'Custom API Keys',
		'custom_api_description': 'Access to our custom API endpoints for advanced AI model integration',
		'refresh': 'Refresh',
		'resource_usage': 'Resource Usage',
		'in_x_days': 'in 8 days',
		'usage_resets': 'Usage resets',
		'hero_title': 'All Your AI Models\nin One Place',
		'refresh_data': 'Refresh Data',
		'explore_plans': 'Explore Plans',
		'usage_period': 'Usage Period',
		'subscription_active': 'Subscription Active',
		'usage_resets_on': 'Usage resets on',
		'usage_summary': 'Usage Summary',
		'no_billing_history': 'No billing history available',
		'billing_history': 'Billing History',
		'subscription_management_subtitle': 'Manage your plan, billing, and usage',
		'hide_api_key': 'Hide API Key',
		'show_api_key': 'Show API Key',
		'email_verification': 'Email Verification',
		'email_verification_message': 'Please verify your email address to continue using our services.',
		'got_it': 'Got it!',
		'openai_api_key': 'OpenAI API Key',
		'huggingface_api_key': 'Hugging Face API Key',
		'anthropic_api_key': 'Anthropic API Key',
		'openai_api_description': 'Access to OpenAI\'s powerful language models for text generation and analysis',
		'anthropic_api_description': 'Access to Anthropic\'s advanced AI models for conversational AI and natural language processing',
		'upgrade_to_access': 'Upgrade to access this feature',
		'plan_required': 'plan required',
		'starter': 'Starter',
		'pro': 'Pro',
		'enterprise': 'Enterprise',
		'technical_specifications': 'Technical Specifications',
		'gpt4_content_creation_desc': 'Generate high-quality content with our advanced GPT-4 model',
		'gpt4_code_development_desc': 'Develop efficient and maintainable code with our advanced GPT-4 model',
		'gpt4_research_analysis_desc': 'Conduct advanced research and analysis with our advanced GPT-4 model',
		'use_cases': 'Use Cases',
		'try_demo_description': 'Experience our AI models in action with our interactive demo',
		'try_model_now': 'Try Model Now',
		'try_for_free': 'View Details',
		'architecture': 'Architecture',
		'capabilities': 'Capabilities',
		'dalle3_digital_art_desc': 'Generate high-quality digital art with DALL-E 3',
		'dalle3_marketing_visuals_desc': 'Create eye-catching marketing visuals with DALL-E 3',
		'dalle3_product_design_desc': 'Design visually appealing products with DALL-E 3',
		'whisper_meeting_transcription_desc': 'Transcribe meetings accurately with Whisper',
		'whisper_subtitle_generation_desc': 'Generate subtitles for videos with Whisper',
		'whisper_voice_commands_desc': 'Control devices with voice commands using Whisper',
		'stable-diffusion_concept_art_desc': 'Create stunning concept art with Stable Diffusion',
		'stable-diffusion_image_editing_desc': 'Edit images with precision using Stable Diffusion',
		'stable-diffusion_asset_generation_desc': 'Generate high-quality assets with Stable Diffusion',
		'claude_data_analysis_desc': 'Analyze data effectively with Claude',
		'claude_content_writing_desc': 'Write high-quality content with Claude',
		'claude_task_automation_desc': 'Automate tasks efficiently with Claude',
		'llama_language_processing_desc': 'Process language effectively with LLaMA',
		'llama_text_generation_desc': 'Generate text effectively with LLaMA',
		'llama_custom_applications_desc': 'Develop custom applications with LLaMA',
		'model_card_tokens': 'Tokens',
		'image_models': 'Image Models',
		'speech_models': 'Speech Models',
		'back_to_login': 'Back to Login',
		'send_reset_password_email': 'Send Email',
		'reset_password_email_sent': 'Reset Password Email Sent',
		'reset_password_check_email': 'Please check your email for a reset password link.',
		'password_updated': 'Password Updated',
		'password_updated_message': 'Your password has been updated successfully. You can now log in with your new password.',
		'new_password_placeholder': 'Enter your new password',
		'confirm_password_placeholder': 'Confirm your new password',
		'invalid_reset_link': 'Invalid reset link',
		'email_required': 'Email is required',
		'reset_link_expired': 'The reset link has expired',
		'password_update_error': 'Error updating password, must be at least 6 characters',
		'passwords_do_not_match': 'Passwords do not match',
		'payment_method': 'Payment Method',
		'payment_method_description': 'Secure your subscription by adding a payment method. We support major credit cards and various payment options.',
		'add_payment_method': 'Add Payment Method',
		'credit_card': 'Credit Card',
		'secure_payment': 'Secure Payment',
		'premium_features': 'Premium Features',
		'contact_name': 'Name',
		'contact_company': 'Company',
		'contact_email': 'Email',
		'deepseek_demo_response': 'This is a simulated response from DeepSeek-R1-Distill-Qwen-32B. In a real implementation, this would be connected to the actual API.',
		'only_deepseek_available': 'Only DeepSeek is available for now.',
	},
	es: {
		'only_deepseek_available': 'Solo DeepSeek está disponible por ahora.',
		'install_ailive_sdk': 'Instalar el SDK de AILive',
		'configure_api_key': 'Configurar tu clave API',
		'make_first_api_call': 'Hacer tu primera llamada a la API',
		'authentication': 'Autenticación',
		'endpoints': 'Endpoints',
		'response_formats': 'Formatos de respuesta',
		'text_generation': 'Generación de texto',
		'image_processing': 'Procesamiento de imágenes',
		'best_practices': 'Mejores prácticas',
		'error_handling': 'Manejo de errores',
		'rate_limiting': 'Límite de solicitudes',
		'deepseek_demo_response': 'Esta es una respuesta simulada de DeepSeek-R1-Distill-Qwen-32B. En una implementación real, esto estaría conectado a la API real.',
		'terms_table_of_contents': 'Tabla de Contenidos',
		'terms_usage_1': 'El acceso y uso de nuestros modelos de IA está sujeto a estos términos',
		'terms_usage_2': 'Debe mantener credenciales de autenticación válidas',
		'terms_usage_3': 'El uso está limitado a su cuota aprobada y límites de velocidad',
		'terms_usage_4': 'No puede realizar ingeniería inversa o descompilar nuestros servicios',
		'terms_responsibility_1': 'Usted es responsable de toda la actividad bajo su cuenta',
		'terms_responsibility_2': 'No debe utilizar nuestros servicios para fines ilegales',
		'terms_responsibility_3': 'Debe proteger sus claves API y credenciales',
		'terms_responsibility_4': 'Debe cumplir con todas las leyes y regulaciones aplicables',
		'terms_limitation_1': 'Los servicios se proporcionan "tal cual" sin garantía',
		'terms_limitation_2': 'Podemos modificar o descontinuar los servicios en cualquier momento',
		'terms_limitation_3': 'Podemos imponer límites o restricciones de uso',
		'terms_limitation_4': 'La disponibilidad y el rendimiento del servicio pueden variar',
		'terms_intellectual_1': 'Conservamos todos los derechos sobre nuestros servicios y tecnología',
		'terms_intellectual_2': 'Usted conserva los derechos sobre sus datos de entrada',
		'terms_intellectual_3': 'Se aplican los términos de licencia del contenido generado',
		'terms_intellectual_4': 'No puede utilizar nuestras marcas comerciales sin permiso',
		'terms_privacy_1': 'Procesamos los datos como se describe en nuestra Política de Privacidad',
		'terms_privacy_2': 'Debe tener derechos sobre los datos que envíe',
		'terms_privacy_3': 'Podemos recopilar datos de uso y análisis',
		'terms_privacy_4': 'Se aplican las políticas de retención de datos',
		'contact_email': 'Correo Electrónico',
		'contact_company': 'Empresa',
		'contact_name': 'Nombre',
		'premium_features': 'Características Premium',
		'secure_payment': 'Pago Seguro',
		'credit_card': 'Tarjeta de Crédito',
		'add_payment_method': 'Agregar Método de Pago',
		'payment_method_description': 'Asegura tu suscripción agregando un método de pago. Soportamos tarjetas de crédito principales y varias opciones de pago.',
		'payment_method': 'Método de Pago',
		'passwords_do_not_match': 'Las contraseñas no coinciden',
		'password_update_error': 'Error al actualizar la contraseña, debe tener al menos 6 caracteres',
		'reset_link_expired': 'El enlace de restablecimiento ha expirado',
		'email_required': 'El correo electrónico es obligatorio',
		'invalid_reset_link': 'Enlace de restablecimiento de contraseña inválido',
		'confirm_password_placeholder': 'Confirma tu nueva contraseña',
		'new_password_placeholder': 'Ingresa tu nueva contraseña',
		'password_updated_message': 'Tu contraseña ha sido actualizada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.',
		'password_updated': 'Contraseña Actualizada',
		'reset_password_check_email': 'Por favor, revisa tu correo electrónico para un enlace de restablecimiento de contraseña.',
		'reset_password_email_sent': 'Email de Restablecimiento de Contraseña Enviado',
		'send_reset_password_email': 'Enviar correo electrónico',
		'back_to_login': 'Volver al Inicio de Sesión',
		'reset_password_subtitle': 'Ingresa tu dirección de correo electrónico para restablecer tu contraseña',
		'speech_models': 'Modelos de Voz',
		'image_models': 'Modelos de Imagen',
		'model_card_tokens': 'Tokens',
		'llama_custom_applications_desc': 'Desarrolla aplicaciones personalizadas con LLaMA',
		'llama_text_generation_desc': 'Genera texto de manera efectiva con LLaMA',
		'llama_language_processing_desc': 'Procesa el lenguaje de manera efectiva con LLaMA',
		'claude_task_automation_desc': 'Automatiza tareas de manera eficiente con Claude',
		'claude_content_writing_desc': 'Escribe contenido de alta calidad con Claude',
		'claude_data_analysis_desc': 'Analiza datos de manera efectiva con Claude',
		'stable-diffusion_asset_generation_desc': 'Genera activos de alta calidad con Stable Diffusion',
		'stable-diffusion_image_editing_desc': 'Edita imágenes con precisión con Stable Diffusion',
		'stable-diffusion_concept_art_desc': 'Crea arte conceptual impresionante con Stable Diffusion',
		'whisper_voice_commands_desc': 'Controla dispositivos con comandos de voz usando Whisper',
		'whisper_subtitle_generation_desc': 'Genera subtítulos para videos con Whisper',
		'whisper_meeting_transcription_desc': 'Transcribe reuniones con precisión con Whisper',
		'dalle3_product_design_desc': 'Diseña productos visualmente atractivos con DALL-E 3',
		'dalle3_marketing_visuals_desc': 'Crea visuales de marketing impactantes con DALL-E 3',
		'dalle3_digital_art_desc': 'Generación de arte digital de última generación con DALL·E 3',
		// Technical Specifications Translations
		// Architecture
		'gpt4_architecture_1': 'Arquitectura basada en transformadores con 1.76T parámetros',
		'gpt4_architecture_2': 'Capacidades multimodales con comprensión de texto e imagen',
		'dalle3_architecture_1': 'Generación de imágenes basada en difusión con guía CLIP avanzada',
		'dalle3_architecture_2': 'Composición de imágenes avanzada y preservación de estilo',
		'whisper_architecture_1': 'Arquitectura codificador-decodificador con soporte multilingüe',
		'whisper_architecture_2': 'Resistencia robusta al ruido y adaptación de acentos',
		'stable_diffusion_architecture_1': 'Modelo de difusión latente con backbone UNet',
		'stable_diffusion_architecture_2': 'Entrenamiento e inferencia eficientes en memoria',
		'claude_architecture_1': 'IA Constitucional con capacidades avanzadas de razonamiento',
		'claude_architecture_2': 'Comprensión avanzada del contexto y adaptación de tareas',
		'llama_architecture_1': 'Transformador de código abierto con escalado eficiente',
		'llama_architecture_2': 'Escalado eficiente de parámetros y capacidades de ajuste fino',

		// Capabilities
		'gpt4_capability_1': 'Capacidades avanzadas de razonamiento y resolución de problemas',
		'gpt4_capability_2': 'Respuestas contextuales con alta precisión',
		'dalle3_capability_1': 'Generación de imágenes fotorrealistas con detalles precisos',
		'dalle3_capability_2': 'Control avanzado de composición y estilo artístico',
		'whisper_capability_1': 'Transcripción precisa en más de 100 idiomas',
		'whisper_capability_2': 'Transcripción y traducción en tiempo real',
		'stable_diffusion_capability_1': 'Generación y edición de imágenes de alta calidad',
		'stable_diffusion_capability_2': 'Inferencia rápida con resultados de calidad',
		'claude_capability_1': 'Realización y análisis de tareas complejas',
		'claude_capability_2': 'Explicaciones detalladas y razonamiento',
		'llama_capability_1': 'Comprensión y generación eficiente del lenguaje',
		'llama_capability_2': 'Personalizable para casos de uso específicos',

		'capabilities': 'Capacidades',
		'architecture': 'Arquitectura',
		"try_for_free": "Ver Detalles",
		"try_model_now": "Prueba el modelo ahora",
		'try_demo_description': 'Experimenta nuestros modelos de IA en acción con nuestra demo interactiva',
		'use_cases': 'Casos de Uso',
		'gpt4_research_analysis_desc': 'Realiza análisis avanzados y investigación con nuestro modelo avanzado de GPT-4',
		'gpt4_code_development_desc': 'Desarrolla código eficiente y mantenible con nuestro modelo avanzado de GPT-4',
		'gpt4_content_creation_desc': 'Genera contenido de alta calidad con nuestro modelo avanzado de GPT-4',
		'technical_specifications': 'Especificaciones Técnicas',
		'enterprise': 'Empresarial',
		'pro': 'Profesional',
		'starter': 'Iniciante',
		'plan_required': 'plan requerido',
		'upgrade_to_access': 'Actualiza para acceder a esta característica',
		'anthropic_api_description': 'Acceso a los modelos de IA avanzados de Anthropic para conversación y procesamiento de lenguaje natural',
		'openai_api_description': 'Acceso a los poderosos modelos de lenguaje de OpenAI para generación y análisis de texto',
		'anthropic_api_key': 'Clave API de Anthropic',
		'huggingface_api_key': 'Clave API de Hugging Face',
		'openai_api_key': 'Clave API de OpenAI',
		'got_it': '¡Entendido!',
		'email_verification_message': 'Por favor, verifica tu dirección de correo electrónico para continuar usando nuestros servicios.',
		'email_verification': 'Verificación de Correo Electrónico',
		'show_api_key': 'Mostrar Clave API',
		'hide_api_key': 'Ocultar Clave API',
		'enter_api_key': 'Ingresa la Clave API',
		'save_api_key': 'Guardar Clave API',
		'custom_api_key': 'Claves de API Personalizadas',
		'custom_api_description': 'Acceso a nuestros puntos de conexión de API personalizados para la integración avanzada de modelos de IA',
		'refresh': 'Actualizar',
		'resource_usage': 'Uso de Recursos',
		'in_x_days': 'en 8 días',
		'usage_resets': 'Reseteo de uso',

		// Free Plan
		'downgrade': 'Plan Actual',
		'free_plan': 'Plan Gratuito',
		'free': 'Gratis',
		'free_feature_1': 'Chat de IA Básico',
		'free_feature_2': 'Acceso API Limitado',
		'free_feature_3': 'Soporte Comunitario',

		// Profile Page
		'phone_number': 'Número de Teléfono',
		'enter_phone': 'Ingresa tu número de teléfono',
		'invalid_phone': 'Por favor ingrese un número de teléfono válido',
		'invalid_email': 'Por favor ingrese un correo electrónico válido',
		'username_only_letters': 'El nombre de usuario solo puede contener letras',
		'username_min_length': 'El nombre de usuario debe tener al menos 3 caracteres',
		'profile_description': 'Administra la configuración y preferencias de tu cuenta',
		'profile_updated_successfully': 'Perfil actualizado exitosamente',
		'member_since': 'Miembro desde',
		'edit': 'Editar',
		'enter_username': 'Ingresa tu nombre de usuario',
		'enter_email': 'Ingresa tu correo electrónico',
		'cancel': 'Cancelar',
		'saving': 'Guardando...',
		'save_changes': 'Guardar Cambios',
		'security': 'Seguridad',
		'password': 'Contraseña',
		'last_changed': 'Último cambio',
		'change_password': 'Cambiar Contraseña',
		'current_password': 'Contraseña Actual',
		'new_password': 'Nueva Contraseña',
		'confirm_password': 'Confirmar Contraseña',
		'updating': 'Actualizando...',
		'update_password': 'Actualizar Contraseña',
		'passwords_dont_match': 'Las contraseñas no coinciden',
		'password_too_short': 'La contraseña debe tener al menos 8 caracteres',
		'error_changing_password': 'Error al cambiar la contraseña',
		'connected_services': 'Servicios Conectados',
		'no_connected_services': 'No hay servicios conectados a tu cuenta',

		//Subscription
		'upgrade': 'Comenzar',
		'contact_sales': 'Contactar a Ventas',

		// DeepSeek Model
		'deepseek_description': 'DeepSeek-R1-Distill-Qwen-32B, derivado de DeepSeek-R1, supera a OpenAI-o1-mini.',
		// Auth Popup
		'login': 'Iniciar Sesión',
		'register': 'Registrarse',
		'login_subtitle': '¡Bienvenido de nuevo! Por favor inicia sesión',
		'register_subtitle': 'Crea tu cuenta para comenzar',
		'username': 'Nombre de Usuario',
		'auth_email': 'Correo Electrónico',
		'username_placeholder': 'Ingresa tu nombre de usuario',
		'auth_email_placeholder': 'Ingresa tu correo electrónico',
		'password_placeholder': 'Ingresa tu contraseña',
		'login_button': 'Iniciar Sesión',
		'register_button': 'Crear Cuenta',
		'need_account': '¿No tienes cuenta? Regístrate',
		'have_account': '¿Ya tienes cuenta? Inicia sesión',
		'auth_required_to_use_ai': 'Por favor inicia sesión o regístrate para usar nuestras funciones de IA',
		'login_error': 'Correo o contraseña inválidos',
		'registration_error': 'Error al crear la cuenta. Por favor intenta de nuevo',
		'username_required': 'El nombre de usuario es requerido',
		'username_taken': 'El nombre de usuario ya está en uso',
		'auth_error': 'Error de autenticación. Por favor intenta de nuevo',
		'logout': 'Cerrar Sesión',
		'generating': 'Generando...',

		// Navegación
		'dashboard': 'Panel',
		'profile': 'Perfil',
		'subscription': 'Suscripción',
		'subscription_management': 'Gestión de Suscripción',
		'subscription_management_description': 'Gestiona tu plan de suscripción y detalles de facturación',
		'current_subscription': 'Suscripción Actual',
		'started_on': 'Iniciada el',
		'next_billing_date': 'Próxima fecha de facturación',
		'cancel_subscription': 'Cancelar Suscripción',
		'confirm_cancel': 'Confirmar Cancelación',
		'keep_subscription': 'Mantener Suscripción',
		'subscription_auto_renew_notice': 'Tu suscripción se renovará automáticamente al final del período de facturación',
		'subscription_cancelled': 'Suscripción cancelada exitosamente',
		'subscription_updated': 'Suscripción actualizada exitosamente',
		'change_plan': 'Cambiar Plan',
		'current_plan': 'Plan Actual',
		'subscription_cancelled_success': 'Suscripción cancelada exitosamente',
		'subscription_cancelled_error': 'Error al cancelar la suscripción',
		'subscription_updated_success': 'Suscripción actualizada exitosamente',
		'subscription_updated_error': 'Error al actualizar la suscripción',
		'confirm_cancel_subscription': '¿Estás seguro de que deseas cancelar tu suscripción?',
		'usage_summary': 'Resumen de Uso',
		'usage_period': 'Período de Uso',
		'usage_resets_on': 'Se reinicia el',
		'billing_history': 'Historial de Facturación',
		'date': 'Fecha',
		'description': 'Descripción',
		'amount': 'Monto',
		'invoice': 'Factura',
		'download': 'Descargar',
		'no_billing_history': 'No hay historial de facturación disponible',
		'refresh_data': 'Actualizar Datos',
		'subscription_active': 'Suscripción Activa',
		'subscription_canceled': 'Suscripción Cancelada',
		'subscription_inactive': 'Suscripción Inactiva',
		'subscription_ends': 'Finaliza el',
		'subscription_renews': 'Se renueva el',
		'explore_plans': 'Explorar Planes',
		'need_enterprise_features': '¿Necesitas Características Empresariales?',
		'enterprise_custom_description': 'Obtén un plan personalizado adaptado a las necesidades de tu organización',
		'contact_our_sales_team': 'Contacta a Nuestro Equipo de Ventas',
		'explore_models': 'Explorar Modelos',
		'try_demo': 'Probar Demo',
		'docs': 'Documentación',
		'pricing': 'Precios',
		'contact': 'Contacto',
		'about': 'Acerca de',
		'privacy': 'Privacidad',
		'terms': 'Términos',

		// Configuración
		'language': 'Idioma',
		'english': 'Inglés',
		'spanish': 'Español',
		'french': 'Francés',
		'german': 'Alemán',
		'chinese': 'Chino',
		'japanese': 'Japonés',
		'coming_soon': 'Próximamente',
		'theme': 'Tema',
		'graph_animation': 'Animación de Gráfico',
		'snow_effect': 'Efecto de Nieve',
		'settings': 'Configuración',

		// Página de Inicio
		'hero_title': 'Todos tus Modelos de IA\nen Un Solo Lugar',
		'hero_subtitle': 'Accede a modelos de IA de última generación a través de una plataforma unificada. Construye aplicaciones más inteligentes con nuestra suite completa de servicios de IA.',
		'get_started_button': 'Comenzar',
		'learn_more': 'Saber Más',

		// Sección del Panel
		'dashboard_title': 'Panel de Análisis Potente',
		'dashboard_subtitle': 'Monitorea el rendimiento, uso y métricas de tus modelos de IA en tiempo real con nuestro panel intuitivo.',

		// Sección de Características
		'language_models_title': 'Modelos de Lenguaje',
		'language_models_desc': 'Accede a potentes modelos de lenguaje para conversaciones naturales, generación de contenido y más.',
		'image_generation_title': 'Generación de Imágenes',
		'image_generation_desc': 'Crea imágenes impresionantes a partir de descripciones de texto con modelos de generación de última generación.',
		'speech_recognition_title': 'Reconocimiento de Voz',
		'speech_recognition_desc': 'Convierte voz a texto con alta precisión en múltiples idiomas y acentos.',
		'try_it_now': 'Pruébalo ahora',
		'settings_description': 'Administra la configuración y preferencias de tu cuenta',
		'settings_saved_successfully': 'Configuración guardada exitosamente',
		'dark_mode': 'Modo Oscuro',
		'dark_mode_description': 'Activar o desactivar el modo oscuro',
		'neural_network_background': 'Fondo de Red Neuronal',
		'neural_network_description': 'Activar o desactivar la animación de fondo de red neuronal',
		'email_notifications': 'Notificaciones por Correo Electrónico',
		'email_notifications_description': 'Recibir actualizaciones y notificaciones por correo electrónico',
		'manage': 'Administrar',
		'usage_metrics': 'Métricas de Uso',
		'ai_tools_hub': 'Centro de Herramientas de IA',
		'explore_available_tools': 'Explorar herramientas de IA disponibles',
		'explore_tools': 'Explorar Herramientas',
		'billing_management': 'Gestión de Facturación',
		'view_billing_history': 'Ver Historial de Facturación',
		'manage_payment_methods': 'Administrar Métodos de Pago',
		'api_keys_description': 'Administra tus claves API para acceder a los servicios de IA',
		'save_settings': 'Guardar la configuración',
		'api_keys': 'Claves API',
		'appearance': 'Apariencia',
		'notifications': 'Notificaciones',

		// Página de Precios
		'pricing_title': 'Precios Simples y Transparentes',
		'pricing_subtitle': 'Elige el plan que mejor se adapte a tus necesidades',
		'api_calls_per_month': 'Llamadas API por mes',
		'model_access': 'Acceso a Modelos',
		'email': 'Correo Electrónico',
		'starter_plan': 'Inicial',
		'starter_feature_1': 'Acceso a modelos básicos',
		'starter_feature_2': '5,000 llamadas API por mes',
		'starter_feature_3': 'Soporte estándar',
		'pro_plan': 'Profesional',
		'pro_feature_1': 'Acceso a todos los modelos',
		'pro_feature_2': '50,000 llamadas API por mes',
		'pro_feature_3': 'Soporte prioritario',
		'pro_feature_4': 'Análisis avanzado',
		'enterprise_plan': 'Empresarial',
		'enterprise_feature_1': 'Llamadas API ilimitadas',
		'enterprise_feature_2': 'Soporte dedicado 24/7',
		'enterprise_feature_3': 'Desarrollo de modelos personalizados',
		'enterprise_feature_4': 'Garantías de SLA',
		'enterprise_feature_5': 'Implementación en sitio',
		'monthly': 'mensual',
		'yearly': 'anual',
		'plan_free_description': 'Funciones básicas para uso personal',
		'plan_starter_description': 'Funciones mejoradas para equipos pequeños',
		'plan_pro_description': 'Funciones avanzadas para empresas',
		'plan_enterprise_description': 'Acceso completo para grandes organizaciones',
		'redirecting': 'Redirigiendo...',

		// Contact Page
		'contact_title': 'Contáctanos',
		'contact_subtitle': 'Nos encantaría saber de ti',
		'contact_page_name': 'Nombre',
		'contact_page_email': 'Correo',
		'contact_page_message': 'Mensaje',
		'send_message': 'Enviar Mensaje',
		'contact_send_message': 'Enviar Mensaje',

		// Pie de Página
		'footer_description': 'Construyendo el futuro de la integración de IA',
		'footer_resources': 'Recursos',
		'footer_company': 'Empresa',
		'footer_legal': 'Legal',
		'footer_subscribe': 'Suscríbete a nuestro boletín informativo',
		'subscribe_desc': 'Recibe las ultimas actualizaciones y noticias directamente en tu bandeja de entrada.',
		'subscribe_button': 'Suscribirse',
		'all_rights_reserved': 'Todos los derechos reservados.',
		'social_media': 'Síguenos',
		'twitter': 'Twitter',
		'github': 'GitHub',
		'linkedin': 'LinkedIn',

		// Suscripción y Uso
		'included_features': 'Características incluidas',
		'100_api_calls_per_month': '100 llamadas API por mes',
		'100_mb_storage': '100.00 MB de almacenamiento',
		'5_model_access': 'Acceso a 5 modelos',
		'current_usage': 'Uso actual',
		'api_calls': 'Llamadas API',
		'storage': 'Almacenamiento',
		'upgrade_plan': 'Mejorar plan',
		'subscription_management_subtitle': 'Administra tu plan, facturación y uso',

		// Interactive Demo
		'demo_title': 'Demo Interactivo',
		'demo_subtitle': 'Experimenta nuestros modelos de IA en acción',
		'try_models': 'Prueba Nuestros Modelos',
		'view_examples': 'Ver Ejemplos',

		// Página de Modelos
		'models_title': 'Centro de Modelos de IA',
		'models_subtitle': 'Explora nuestra colección de modelos de IA de última generación',
		'filter_models': 'Filtrar Modelos',
		'search_models': 'Buscar Modelos',
		'sort_by': 'Ordenar por',
		'category': 'Categoría',
		'all_categories': 'Todas las Categorías',
		'newest': 'Más Reciente',
		'model_name': 'Nombre',
		'no_models_found': 'No se encontraron modelos en esta categoría. Intenta seleccionar una categoría diferente.',
		'version': 'Versión',
		'try_model': 'Probar Modelo',

		// Categorías de Modelos
		'language_models': 'Modelos de Lenguaje',
		'image_generation': 'Generación de Imágenes',
		'speech_recognition': 'Reconocimiento de Voz',
		'computer_vision': 'Visión por Computadora',
		'audio_processing': 'Procesamiento de Audio',

		// Detalles del Modelo
		'model_description': 'Descripción del Modelo',
		'features': 'Características',
		'specifications': 'Especificaciones',
		'requirements': 'Requisitos',
		'documentation': 'Documentación',
		'api_endpoints': 'Endpoints de API',
		'pricing_info': 'Información de Precios',
		'model_version': 'Versión del Modelo',
		'last_updated': 'Última Actualización',
		'status': 'Estado',
		'active': 'Activo',
		'deprecated': 'Obsoleto',
		'beta': 'Beta',

		// Sort Options
		'sort_popular': 'Más Popular',
		'sort_newest': 'Más Reciente',
		'sort_name': 'Nombre',
		'sort_rating': 'Mejor Calificado',

		// Status Messages
		'loading': 'Cargando...',
		'error_loading': 'Error al cargar los modelos',
		'try_again': 'Intentar de Nuevo',
		'no_results': 'No se encontraron resultados',
		'no_results_try_again': 'No se encontraron resultados. Intenta con otros términos de búsqueda.',

		// Actions
		'view_details': 'Ver Detalles',
		'view_docs': 'Ver Documentación',

		// Autenticación
		'sign_in': 'Iniciar Sesión',
		'sign_up': 'Registrarse',
		'sign_out': 'Cerrar Sesión',
		'forgot_password': '¿Olvidaste tu Contraseña?',
		'reset_password': 'Restablecer Contraseña',
		'remember_me': 'Recordarme',

		// Form Labels
		'form_email': 'Correo Electrónico',
		'form_password': 'Contraseña',
		'form_confirm_password': 'Confirmar Contraseña',
		'form_full_name': 'Nombre Completo',
		'form_company': 'Empresa',
		'form_message': 'Mensaje',
		'form_name': 'Nombre',

		// Documentation
		'docs_title': 'Documentación',
		'docs_subtitle': 'Aprende cómo integrar y usar nuestros modelos de IA',
		'quick_start': 'Inicio Rápido',
		'api_reference': 'Referencia de API',
		'examples': 'Ejemplos',
		'guides': 'Guías',

		// Testimonials Section
		'testimonials_title': 'Lo que Dicen Nuestros Usuarios',
		'testimonials_subtitle': 'Descubre cómo AILive está transformando empresas en todo el mundo',
		'testimonial_1_name': 'Sarah Johnson',
		'testimonial_1_role': 'CTO en TechCorp',
		'testimonial_1_text': 'La plataforma ha optimizado nuestro proceso de integración de IA y reducido significativamente nuestro tiempo de llegada al mercado.',
		'testimonial_2_name': 'Michael Chen',
		'testimonial_2_role': 'Desarrollador Principal en InnovateLabs',
		'testimonial_2_text': 'AILive ha transformado nuestro flujo de trabajo de desarrollo. Los modelos son increíblemente precisos y la API es muy fácil de usar.',
		'testimonial_3_name': 'Emma Rodriguez',
		'testimonial_3_role': 'Directora de Investigación en IA',
		'testimonial_3_text': '¡Las capacidades de ajuste fino y el monitoreo del rendimiento del modelo han superado nuestras expectativas. Altamente recomendado!',
		'testimonial_4_name': 'David Wilson',
		'testimonial_4_role': 'Director de Innovación',
		'testimonial_4_text': 'Las perspectivas de rendimiento del modelo y las sugerencias de optimización nos han ayudado a lograr mejoras notables.',
		'testimonial_5_name': 'Laura Garcia',
		'testimonial_5_role': 'VP de Tecnología',
		'testimonial_5_text': 'Equipo de soporte excepcional y documentación completa. Han hecho que nuestro viaje con la IA sea fluido y exitoso.',
		'testimonial_6_name': 'Robert Martinez',
		'testimonial_6_role': 'CTO en TechCorp',
		'testimonial_6_text': 'La fiabilidad y escalabilidad de la plataforma han sido cruciales para nuestra implementación empresarial.',

		// Interactive Demo Sections
		'demo_tabs_title': 'Prueba Nuestros Modelos',
		'tab_text_generation': 'Generación de Texto',
		'tab_image_generation': 'Generación de Imágenes',
		'tab_speech_recognition': 'Reconocimiento de Voz',
		'tab_code_generation': 'Generación de Código',
		'input_placeholder': 'Ingresa tu prompt aquí...',
		'generate_button': 'Generar',
		'processing': 'Procesando...',
		'sample_prompts': 'Prompts de Ejemplo',
		'clear_input': 'Limpiar',
		'copy_result': 'Copiar',
		'download_result': 'Descargar',
		'share_result': 'Compartir',
		'model_settings': 'Configuración del Modelo',
		'temperature': 'Temperatura',
		'max_length': 'Longitud Máxima',
		'frequency_penalty': 'Penalización de Frecuencia',
		'presence_penalty': 'Penalización de Presencia',

		// Model Card Details
		'model_card_metrics': 'Métricas de Rendimiento',
		'model_card_latency': 'Latencia',
		'model_card_availability': 'Disponibilidad',
		'model_card_accuracy_metric': 'Precisión',
		'model_card_pricing': 'Planes de Precios',
		'model_card_starter': 'Inicial',
		'model_card_pro': 'Profesional',
		'model_card_enterprise': 'Empresarial',
		'model_card_features': 'Características Principales',
		'model_card_try': 'Probar Modelo',
		'model_card_learn_more': 'Más Información',
		'model_card_version_info': 'Información de Versión',
		'model_card_last_updated': 'Última Actualización',
		'model_card_changelog': 'Registro de Cambios',
		'model_card_documentation': 'Documentación',
		'model_card_examples': 'Ejemplos',
		'model_card_limitations': 'Limitaciones',
		'model_card_use_cases': 'Casos de Uso',
		'model_card_ready_to_start': '¿Listo para Empezar?',
		'model_card_start_building': 'Comenzar a Construir',
		'model_card_performance': 'Rendimiento',
		'model_card_context_length': 'Longitud de Contexto',
		'model_card_resolution': 'Resolución',
		'model_card_token_length': 'Longitud de Token',
		'model_card_languages': 'Idiomas Soportados',
		'model_card_starter_desc': 'Acceso básico con funciones estándar',
		'model_card_pro_desc': 'Funciones avanzadas con soporte prioritario',
		'model_card_enterprise_desc': 'Soluciones personalizadas con soporte dedicado',
		'gpt4_desc': 'Último modelo GPT-4 con capacidades mejoradas',
		'llama2_desc': 'LLM de código abierto con rendimiento competitivo',
		'stable_diffusion_xl_desc': 'Generación avanzada de imágenes con SDXL',
		'whisper_desc': 'Reconocimiento de voz preciso en múltiples idiomas',
		'dalle3_desc': 'Generación de imágenes de última generación con DALL·E 3',
		'llama_desc': 'Modelo de lenguaje de código abierto de alto rendimiento',

		// Interactive Demo Page
		'demo_text_generation_desc': 'Experimenta el poder de nuestro modelo de lenguaje más avanzado.',
		'demo_image_generation_desc': 'Genera imágenes impresionantes a partir de descripciones textuales.',
		'demo_speech_recognition_desc': 'Convierte voz a texto con excepcional precisión.',
		'demo_code_generation_desc': 'Genera código con nuestro modelo eficiente y potente.',
		'demo_input_placeholder': 'Ingresa tu prompt aquí...',
		'demo_send_message': 'Enviar Mensaje',
		'generated_image': 'Imagen generada',
		'start_recording': 'Iniciar Grabación',
		'stop_recording': 'Detener Grabación',

		// Model Features
		'feature_natural_language': 'Procesamiento de Lenguaje Natural',
		'feature_content_generation': 'Generación de Contenido',
		'feature_code_assistance': 'Asistencia de Código',
		'feature_text_to_image': 'Generación de Imágenes desde Texto',
		'feature_image_editing': 'Edición de Imágenes',
		'feature_style_transfer': 'Transferencia de Estilo',
		'feature_speech_to_text': 'Voz a Texto',
		'feature_language_detection': 'Detección de Idioma',
		'feature_accent_handling': 'Manejo de Acentos',
		'feature_image_generation': 'Generación de Imágenes',
		'feature_inpainting': 'Retoque de Imágenes',
		'feature_outpainting': 'Extensión de Imágenes',
		'feature_task_assistance': 'Asistencia de Tareas',
		'feature_research': 'Investigación',
		'feature_analysis': 'Análisis',
		'feature_text_generation': 'Generación de Texto',
		'feature_translation': 'Traducción',
		'feature_classification': 'Clasificación',

		// Model-Specific Translations
		'tab_claude': 'Asistente Claude',
		'claude_desc': 'Asistente de IA avanzado de Anthropic enfocado en interacciones útiles, honestas y seguras',
		'claude_input_placeholder': 'Pregunta lo que quieras a Claude...',
		'claude_demo_response': 'Mi objetivo es ser útil siendo directo y honesto. Te ayudaré con análisis, escritura y diversas tareas manteniendo altos estándares éticos.',
		'tab_stable_diffusion': 'Stable Diffusion',
		'stable_diffusion_desc': 'Generación avanzada de imágenes con control preciso y salidas de alta calidad',
		'stable_diffusion_prompt_placeholder': 'Describe la imagen que quieres generar en detalle...',
		'deepseek_input_placeholder': 'Escribe tu mensaje aquí...',
		'top_p': 'Top P',
		'max_tokens': 'Tokens máximos',
		'top_k': 'Top K',
		'deepseek_model_description': 'DeepSeek-R1-Distill-Qwen-32B es un modelo destilado de DeepSeek-R1 basado en Qwen2.5. Supera a OpenAI-o1-mini en varios puntos de referencia.',
		'stable_diffusion_negative_placeholder': 'Describe lo que no quieres ver en la imagen...',
		'positive_prompt': 'Prompt Positivo',
		'negative_prompt': 'Prompt Negativo',
		'steps': 'Pasos de Generación',
		'guidance_scale': 'Escala de Guía',
		'gpt_demo_response': 'Esta es una respuesta simulada de GPT-4. En una implementación real, esto estaría conectado a la API real.',
		'llama_demo_response': 'Esta es una respuesta simulada de LLaMA usando temperatura {temp} y tokens máximos {tokens}.',
		'speech_demo_transcript': 'Esta es una transcripción simulada. En una implementación real, esto usaría la API Web Speech o similar.',
		'llama_input_placeholder': 'Ingresa tu prompt para LLaMA...',
		'image_input_placeholder': 'Describe la imagen que quieres generar...',

		// Trusted Section
		'trusted_title': 'Confiado por Líderes de la Industria',
		'trusted_description': 'Únete a miles de empresas en todo el mundo que confían en nuestras soluciones de IA',
		'trusted_card_1_title': 'Soluciones Empresariales',
		'trusted_card_1_desc': 'Integración de IA personalizada para operaciones a gran escala',
		'trusted_card_2_title': 'Herramientas para Desarrolladores',
		'trusted_card_2_desc': 'APIs y SDKs potentes para una implementación sin problemas',
		'trusted_card_3_title': 'Soporte y Capacitación',
		'trusted_card_3_desc': 'Recursos completos y asistencia experta',

		// Carousel
		'carousel_explore': 'Explorar Modelos de IA',
		'carousel_why_choose': '¿Por qué elegir AILive?',
		'carousel_close': 'Cerrar',
		'carousel_prev': 'Anterior',
		'carousel_next': 'Siguiente',

		// About Page
		'about_title': 'Sobre AILive',
		'about_subtitle': 'Impulsando la Innovación a través de la IA',
		'about_description': 'AILive es una plataforma líder que proporciona modelos y soluciones de IA de última generación. Nuestra misión es hacer que la tecnología de IA avanzada sea accesible y práctica para empresas de todos los tamaños.',
		'about_vision': 'Nuestra Visión',
		'about_vision_text': 'Democratizar la tecnología de IA e impulsar la innovación en todas las industrias.',
		'about_mission': 'Nuestra Misión',
		'about_mission_text': 'Proporcionar soluciones de IA de vanguardia que sean accesibles, confiables y éticas.',
		'about_values': 'Nuestros Valores',
		'about_values_1': 'Innovación',
		'about_values_1_text': 'Constantemente expandiendo los límites de la tecnología de IA',
		'about_values_2': 'Confiabilidad',
		'about_values_2_text': 'Entregando soluciones consistentes y confiables',
		'about_values_3': 'Ética',
		'about_values_3_text': 'Manteniendo altos estándares de ética y responsabilidad en IA',

		// Terms Page
		'terms_title': 'Términos de Servicio',
		'terms_last_updated': 'Última Actualización',
		'terms_intro': 'Por favor, lea estos términos de servicio cuidadosamente antes de usar nuestra plataforma.',
		'terms_acceptance': 'Al acceder o usar nuestro servicio, usted acepta estar sujeto a estos términos.',
		'terms_section_1': 'Términos de Uso',
		'terms_section_2': 'Responsabilidades del Usuario',
		'terms_section_3': 'Limitaciones del Servicio',
		'terms_section_4': 'Propiedad Intelectual',
		'terms_section_5': 'Privacidad y Datos',

		// Privacy Page
		'privacy_title': 'Política de Privacidad',
		'privacy_last_updated': 'Última Actualización',
		'privacy_intro': 'Nos tomamos en serio tu privacidad. Esta política explica cómo recopilamos, usamos y protegemos tu información personal.',
		'privacy_section_1': 'Recopilación de Datos',
		'privacy_section_2': 'Uso de Datos',
		'privacy_section_3': 'Protección de Datos',
		'privacy_section_4': 'Derechos del Usuario',
		'privacy_section_5': 'Información de Contacto',
		'privacy_collection_1': 'Recopilamos la información que nos proporcionas directamente al usar nuestros servicios.',
		'privacy_collection_2': 'Recopilamos automáticamente cierta información sobre tu dispositivo y uso de nuestros servicios.',
		'privacy_collection_3': 'Utilizamos cookies y tecnologías de seguimiento similares para mejorar tu experiencia.',
		'privacy_collection_4': 'Podemos recopilar información de servicios de terceros con tu consentimiento.',
		'privacy_usage_1': 'Usamos tu información para proporcionar y mejorar nuestros servicios.',
		'privacy_usage_2': 'Tus datos nos ayudan a personalizar y optimizar tu experiencia.',
		'privacy_usage_3': 'Analizamos patrones de uso para mejorar la funcionalidad de nuestra plataforma.',
		'privacy_usage_4': 'Podemos usar tu información con fines de marketing con tu consentimiento.',
		'privacy_protection_1': 'Implementamos medidas de seguridad estándar de la industria para proteger tus datos.',
		'privacy_protection_2': 'Tu información está cifrada durante la transmisión y almacenamiento.',
		'privacy_protection_3': 'Revisamos y actualizamos regularmente nuestras prácticas de seguridad.',
		'privacy_protection_4': 'El acceso a tus datos está estrictamente controlado y monitoreado.',
		'privacy_rights_1': 'Tienes derecho a acceder a tu información personal.',
		'privacy_rights_2': 'Puedes solicitar correcciones en tus datos.',
		'privacy_rights_3': 'Puedes solicitar la eliminación de tu información.',
		'privacy_rights_4': 'Puedes optar por no participar en ciertas actividades de procesamiento de datos.',
		'privacy_contact_1': 'Para consultas relacionadas con la privacidad, contacta a nuestro Oficial de Protección de Datos.',
		'privacy_contact_2': 'Envíanos un correo a privacy@ailive.com',
		'privacy_contact_3': 'Tiempo de respuesta: Dentro de 48 horas',
		'privacy_contact_4': 'Estamos comprometidos a atender tus inquietudes de privacidad con prontitud.',

		// Popup de Testimonios
		'testimonial_metrics': 'Métricas de Rendimiento',
		'testimonial_close': 'Cerrar Detalles',
		'testimonial_rating': 'Calificación',
		'testimonial_company': 'Empresa',
		'testimonial_role': 'Cargo',

		// Traducciones de Métricas
		'metric_accuracy': 'Precisión',
		'metric_responsetime': 'Tiempo de Respuesta',
		'metric_uptime': 'Disponibilidad',
		'metric_modelsdeployed': 'Modelos Desplegados',
		'metric_averagelatency': 'Latencia Promedio',
		'metric_successrate': 'Tasa de Éxito',
		'metric_throughput': 'Rendimiento',
		'metric_errorrate': 'Tasa de Error',
		'metric_costsavings': 'Ahorro de Costos',
		'metric_timetomarket': 'Tiempo al Mercado',
		'metric_usersatisfaction': 'Satisfacción del Usuario',
		'metric_roi': 'Retorno de Inversión',
		'metric_modelaccuracy': 'Precisión del Modelo',
		'metric_inferencespeed': 'Velocidad de Inferencia',
		'metric_costreduction': 'Reducción de Costos',
		'metric_apiuptime': 'Disponibilidad de API',
		'metric_integrationtime': 'Tiempo de Integración',
		'metric_supportresponse': 'Respuesta de Soporte',

		// Carousel Cards
		'carousel_card_1_title': 'Modelos de IA Avanzados',
		'carousel_card_1_desc': 'Accede a modelos de IA de vanguardia a través de nuestra plataforma unificada',
		'carousel_card_2_title': 'Integración Sencilla',
		'carousel_card_2_desc': 'Integración API simple con documentación completa',
		'carousel_card_3_title': 'Soluciones Escalables',
		'carousel_card_3_desc': 'Infraestructura empresarial que crece contigo',

		// Carousel Popups
		'explore_models_title': 'Explorar Modelos de IA',
		'explore_models_desc': 'Descubre nuestra completa suite de modelos de IA de última generación listos para integrar',
		'why_choose_title': '¿Por qué elegir AILive?',
		'why_choose_desc': 'Plataforma líder para integración de IA con fiabilidad y soporte de nivel empresarial',

		// Card Descriptions in Popups
		'card_performance_title': 'Alto Rendimiento',
		'card_performance_desc': 'Precisión y tiempos de respuesta líderes en la industria',
		'card_security_title': 'Seguridad Empresarial',
		'card_security_desc': 'Características de seguridad avanzadas y estándares de cumplimiento',
		'card_support_title': 'Soporte 24/7',
		'card_support_desc': 'Soporte técnico dedicado y documentación completa',

		'models_available': 'Modelos Disponibles',
		'api_requests_daily': 'Peticiones API Diarias',
		'enterprise_clients': 'Clientes Empresariales',
		'uptime_sla': 'SLA de Disponibilidad',
		'stats_title': 'AILive en Números',
		'ready_to_transform': '¿Listo para transformar tu flujo de trabajo de IA?',

		// Dashboard Metrics
		'dashboard_model_performance': 'Rendimiento del Modelo IA',
		'dashboard_accuracy': 'Precisión',
		'dashboard_latency': 'Latencia',
		'dashboard_uptime': 'Disponibilidad',
		'dashboard_api_usage': 'Uso de API',
		'dashboard_model_training': 'Entrenamiento del Modelo',

		// Contact Form Fields
		'contact_form_name': 'Nombre',
		'contact_form_email': 'Correo',
		'contact_company_name': 'Nombre de la Empresa',
		'contact_phone': 'Número de Teléfono',
		'contact_model': 'Modelo de IA de Interés',
		'contact_message': 'Mensaje',
		'contact_submit': 'Enviar Mensaje',
		'contact_placeholder_name': 'Ingresa tu nombre',
		'contact_placeholder_email': 'Ingresa tu correo electrónico',
		'contact_placeholder_company': 'Ingresa el nombre de tu empresa',
		'contact_placeholder_phone': '+1 (555) 000-0000',
		'contact_placeholder_message': 'Ingresa tu mensaje',
		'contact_select_model': 'Selecciona un modelo',

		// Información Adicional de Contacto
		'contact_email_label': 'Correo',
		'contact_phone_label': 'Teléfono',
		'contact_hours_label': 'Horario de Oficina',
		'contact_hours_value': 'Lun-Vie, 9am-6pm EST',
		'multiple_models': 'Múltiples Modelos',

		// Stable Diffusion
		'stable_diffusion_negative_prompt_placeholder': 'Ingresa los elementos que NO deseas ver en la imagen (opcional)',
		'generate_image': 'Generar Imagen',

		// Especificaciones de Modelos
		'context_length': 'Longitud de Contexto',
		'up_to': 'Hasta',
		'tokens': 'tokens',
		'code_generation_desc': 'Genera cu00f3digo eficiente y mantenible con nuestros modelos avanzados.',
		'model_context_length': 'Contexto',
		'supported': 'soportados',
		'stable_diffusion': 'Difusión Estable',
		'month_abbr': 'mes',

		// Configuración de Idioma
		'language_settings': 'Configuración de Idioma',
		'language_settings_description': 'Elige tu idioma preferido',
		'language_english': 'Inglés',
		'language_spanish': 'Español',
		'language_french': 'Francés',
		'language_german': 'Alemán',
		'language_chinese': 'Chino',
		'language_japanese': 'Japonés',
		'language_coming_soon': 'Próximamente',
		'speech': 'Voz',
		'image': 'Imagen',
		'custom': 'Personalizado',

		// Características de Suscripción
		'browser_agent_description': 'Automatización del navegador con IA para interacciones web y recolección de datos sin problemas',
		'deep_research_description': 'Capacidades avanzadas de investigación con IA para análisis e insights completos',
		'scraping_agent_description': 'Extracción inteligente de datos y automatización de formularios usando algoritmos avanzados de IA',
		'ai_assistant_description': 'Asistente de IA mejorado con capacidades avanzadas y comprensión contextual',
		'custom_models_description': 'Crea y ajusta modelos de IA personalizados adaptados a tus necesidades específicas',
		'subscription_type': 'Tipo de Suscripción',
		'subscriptions': 'Suscripciones',
		'enterprise_support_message': 'Obtén acceso prioritario a nuestro equipo de soporte dedicado 24/7',
		'huggingface_api_description': 'Accede a modelos de IA de última generación de Hugging Face para generación de texto, procesamiento de imágenes y más',
		'advanced_chat_description': 'Capacidades de chat mejoradas con memoria contextual y 25 llamadas API diarias para mejores conversaciones',
		'pro_chat_description': 'Sistema de chat profesional con funciones avanzadas, comprensión contextual y 100 llamadas API diarias',
		'model_fine_tuning_description': 'Personaliza y optimiza modelos de IA con tus propios datos para soluciones específicas de tu industria',
		'enterprise_chat_description': 'Sistema de chat empresarial con llamadas API ilimitadas, integraciones personalizadas y soporte dedicado',

		// Panel de Control
		'starter_dashboard_welcome': 'Bienvenido a tu Panel Inicial',
		'pro_dashboard_welcome': 'Bienvenido a tu Panel Pro',
		'enterprise_dashboard_welcome': 'Bienvenido a tu Panel Empresarial',
		'enterprise_dashboard_subtitle': 'Accede a todas las funciones premium y soluciones personalizadas',
		'api_calls_remaining': 'Llamadas API Restantes',
		'unlimited': 'Ilimitado',
		'customize_models': 'Personalizar Modelos',
		'launch_tool': 'Iniciar Herramienta',
		'enterprise_support': 'Soporte Empresarial 24/7',
		'enterprise_support_description': 'Obtén soporte prioritario de nuestro equipo dedicado de expertos en IA',
		'contact_support': 'Contactar Soporte',
		'schedule_call': 'Programar Llamada',

		// Suscripción
		'subscription_plans': 'Elige tu Plan de IA',
		'choose_plan_description': 'Selecciona el plan que mejor se adapte a tus necesidades de desarrollo de IA',
		'subscription_monthly_billing': 'Mensual',
		'subscription_yearly_billing': 'Anual',
		'subscription_save': 'Ahorra',
		'subscription_with_yearly_billing': 'con facturación anual',
		'subscription_most_popular': 'Más Popular',
		'subscription_current_plan_es': 'Plan Actual',
		'subscription_get_started': 'Comenzar',
		'subscription_month': 'mes',
		'subscription_year': 'año',
		'popular': 'Popular',

		// Plan features translations
		'Basic AI Chat': 'Chat de IA Básico',
		'5 API calls/day': '5 llamadas API/día',
		'Community Support': 'Soporte Comunitario',
		'Standard Response Time': 'Tiempo de Respuesta Estándar',
		'Hugging Face API Access': 'Acceso a API de Hugging Face',
		'Browser Agent': 'Agente de Navegador',
		'Advanced Chat with 25 API calls/day': 'Chat Avanzado con 25 llamadas API/día',
		'Priority Support': 'Soporte Prioritario',
		'All Starter Features': 'Todas las Funciones Iniciales',
		'Scraping Agent': 'Agente de Extracción de Datos',
		'Deep Research': 'Investigación Profunda',
		'AI Assistant with 100 API calls/day': 'Asistente de IA con 100 llamadas API/día',
		'Premium Support': 'Soporte Premium',
		'All Pro Features': 'Todas las Funciones Pro',
		'Custom Models': 'Modelos Personalizados',
		'Model Fine-tuning': 'Ajuste Fino de Modelos',
		'Unlimited API Calls': 'Llamadas API Ilimitadas',
		'24/7 Dedicated Support': 'Soporte Dedicado 24/7',
		'Custom Integrations': 'Integraciones Personalizadas',
	}
}

const LanguageContext = createContext<LanguageContextType>({
	currentLanguage: 'en',
	setLanguage: () => { },
	t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
	const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
		// Get language from localStorage or default to 'en'
		const savedLanguage = localStorage.getItem('preferredLanguage')
		return (savedLanguage === 'en' || savedLanguage === 'es') ? savedLanguage : 'en'
	})

	const setLanguage = (lang: Language) => {
		// Save language to localStorage
		localStorage.setItem('preferredLanguage', lang)
		setCurrentLanguage(lang)
	}

	const t = (key: string): string | string[] => {
		return translations[currentLanguage][key] || key
	}

	return (
		<LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
			{children}
		</LanguageContext.Provider>
	)
}

export function useLanguage() {
	const context = useContext(LanguageContext)
	if (!context) {
		throw new Error('useLanguage must be used within a LanguageProvider')
	}
	return context
}
